

server:
  port: ${PORT}
  servlet:
    context-path: /pet-service
spring:
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

jwt:
  signerKey: "+0FYCfYMCh5Eb6gT1W5fd971heL9xlk54GZJN/4Gd5kn5QxZehHWh+t5kJ6l5dy+"
  valid-duration: 10 # 1 hour
  refresh-duration: 60 # 24 hours