server:
  port: 8080
  servlet:
    context-path: /pet-service

spring:
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: jdbc:mysql://localhost:3306/pet?createDatabaseIfNotExist=true
    username: root
    password: 01665846484
    driver-class-name: com.mysql.cj.jdbc.Driver
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

jwt:
  signerKey: "+0FYCfYMCh5Eb6gT1W5fd971heL9xlk54GZJN/4Gd5kn5QxZehHWh+t5kJ6l5dy+"
  valid-duration: 10 # 10 minutes
  refresh-duration: 60 # 60 minutes